_("That clock seems to be late!")
_("Aw, a midget yeti, how cute!")
_("I'd better not touch this ... What if it explodes??")
_("Closed. We are all imprisoned here ...")
_("No. I certainly won't climb up there!")
_("The entrance to the Inn.")
_("That's the guard's house.")
_("There's a plaque that reads \"Tristan Illig\".")
_("Hm. There are plenty of books on singing inside.")
_("Locked. The plaque reads \"Bregon Arwold\".")
_("Locked. The plaque reads \"Jelom Rasgar\".")
_("The plaque on that chest reads \"Alek Endhelm\".")
_("I doubt Master Fingolson would be happy if I went through his things ...")
_("Hm, nothing hidden in there!")
_("I have already bathed this month!")
_("No, I won't touch my mistress' belongings!")
_("Mmmh ... this wine is really tasty!")
_("I'm sure Master Redwyne won't mind if I take a sip.")
_("Hic! Whoa, that's quite strong!")
_("'Made in Cirdanth', now that's more like it!")
_("'Made in Uzdun' kal'? How cheap is this Master Redwyne?")
_("\"Teach yourself Elvish in 21 days\"?")
_("\"There and back again\", how unimaginative!")
_("Oh dear, \"The Art of making Yetis\", by R. Frostbloom")
_("This is nothing compared to Lady Silverhair's reading room!")
_("Hey, that looks like Adonthell!")
_("I cannot rest when my mistress needs me!")
_("An old, dusty chest.")
_("Lady Silverhair's luggage, but not what I am looking for.")
_("An old, empty crate!")

